//! One file per problem: `pNNNN_snake_case.rs` (the `p` prefix avoids invalid module names
//! that start with a digit, matching `NNNN_slug.py` in the Python tree).
//!
//! Module list is generated by `build.rs` into `_mod_autogen.rs`.

include!("_mod_autogen.rs");
